In [1]:
# intalar el paquete, en caso de no tener instalado el anaconda ya que ahi ya viene
# pip install numpy

import numpy as np

In [3]:
# arreglos
print(type([1,2,3]))
# tuplas
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
np.zeros([5,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((7,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.arange(-4,4)

array([-4, -3, -2, -1,  0,  1,  2,  3])

In [50]:
arreglo_pares = np.arange(0,20,2)

In [29]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4)) 
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [51]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [65]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [68]:
# suma
a+b

array([15, 15, 15])

In [69]:
# resta
a-b

array([5, 5, 5])

In [70]:
# multiplicacion
a*b

array([50, 50, 50])

In [71]:
# division
a/b

array([2., 2., 2.])

In [123]:
c = np.arange(16).reshape(4,2,2)
d = np.arange(0,32,2).reshape(4,2,2)

In [118]:
d = np.arange(0,32,2).reshape(4,2,2)

In [78]:
# mod
a*10

array([100, 100, 100])

In [90]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [143]:
arreglo_muestra[(arreglo_muestra > 5)&(arreglo_muestra%2 == 0)&(arreglo_muestra<16)]

array([ 6,  8, 10, 12, 14])

In [145]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [147]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [148]:
# producto punto
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [149]:
# producto punto
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [150]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
arreglo_doce.sum()

66

In [152]:
arreglo_doce.min()

0

In [153]:
arreglo_doce.max()

11

In [160]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])